# Generated by Django 3.0.4 on 2020-03-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='French',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('owen_name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('profile_pic', models.ImageField(upload_to='image/')),
                ('cover_pic', models.ImageField(upload_to='image/')),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=12)),
                ('address', models.TextField(max_length=100)),
                ('discription', models.TextField(max_length=300)),
                ('Register_date', models.DateField()),
            ],
        ),
    ]
