# Generated by Django 3.0.4 on 2020-03-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('french', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='french',
            old_name='name',
            new_name='branch_name',
        ),
    ]
