# Generated by Django 3.0.4 on 2020-03-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('french', '0002_auto_20200319_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='french',
            old_name='owen_name',
            new_name='owener_name',
        ),
    ]
