# Generated by Django 3.0.4 on 2020-03-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('french', '0003_auto_20200319_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='french',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
